name: Solvraevene

options:
  bundleIdPrefix: dk.haugaard

settings:
  DEVELOPMENT_TEAM: 77GX5T6B82
  CODE_SIGN_STYLE: Automatic

targets:
  Solvraevene:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Solvraevene
    resources:
      - Solvraevene/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: dk.haugaard.solvraevene
      INFOPLIST_FILE: Solvraevene/Info.plist
      DEVELOPMENT_TEAM: 77GX5T6B82
      CODE_SIGN_STYLE: Automatic
