default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier: ["dk.haugaard.solvraevene", "dk.haugaard.solvraevene.widget"],
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: Base64.strict_encode64("x-access-token:#{ENV['MATCH_GIT_TOKEN']}"),
      readonly: false,
      api_key: api_key
    )

    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"]
    )

build_app(
  project: "Solvraevene.xcodeproj",
  scheme: "Solvraevene",
  configuration: "Release",
  export_method: "app-store",
  disable_xcpretty: true,
  export_options: {
    provisioningProfiles: {
      "dk.haugaard.solvraevene" => "match AppStore dk.haugaard.solvraevene",
      "dk.haugaard.solvraevene.widget" => "match AppStore dk.haugaard.solvraevene.widget"
    }
  }
)

upload_to_testflight(
  api_key: api_key,
  notify_external_testers: false,
  skip_waiting_for_build_processing: false
)
  end
end
